### ISSUE TITLE
Document entry types

### ISSUE THREAD

**Issue by gerwitz** [gerwitz/sitewriter#2]
In README or a page? I guess that depends on if we're sharing this with the public.

**Comment by paulrobertlloyd** [comment]
Short inline help text where relevant – possibly alongside a help page linked from the site header perhaps – would be perfect!

**Comment by gerwitz** [comment]
Heh, I guess it looks like we're sharing this with the public.

**Comment by gerwitz** [comment]
Related: let's also document the decision tree: https://indieweb.org/posts#Inferring_post_kinds_from_properties

**Comment by gerwitz** [comment]
README now has a description of the discovery algorithm, and there are basic classes for 11 post types.

Presently, these classes are pretty sparse, so the user will have to "just know" what properties are available for template substitution. So, #31 or #32
