### ISSUE TITLE
Provide additional path/URL components

### ISSUE THREAD

**Issue by paulrobertlloyd** [gerwitz/sitewriter#21]
I’m currently publishing my notes at URL’s with the format `/notes/{{yyyy}}/{{mm}}/{{dd}}-{{hh}}{{mm}}`. However, hours and minutes (as well as seconds and possibly other meta data) is not available for constructing a path or URL. It would be nice to provide more options for users here.

**Comment by gerwitz** [comment]
Added as part of 2ec21291d2cc4adace89ee2b8eea2f0fd99e099d

**Comment by paulrobertlloyd** [comment]
Woo-hoo! Thank-you so much, Hans. Just a note however… the site is currently down. 😬
