### ISSUE TITLE
Can categories also be used as tags?

### ISSUE THREAD

**Issue by paulrobertlloyd** [gerwitz/sitewriter#22]
In the template, there is a categories loop. I assume `categories` is the nomenclature used by the MicroPub API, so it’s up to the user if they want to use those as either tags or categories (or some other taxonomy). If this is the case, it might it be helpful to add some help regarding how you can use categories data (i.e., not just for categories).

**Comment by gerwitz** [comment]
Any variable display in #34 will also show a description that invites the use of `category` as tags
