### ISSUE TITLE
Error reported by MicroPub.rocks: undefined method `store_post&#x27; for nil:NilClass

### ISSUE THREAD

**Issue by paulrobertlloyd** [gerwitz/sitewriter#24]
Thought I’d try to go through each of the tests on <https://micropub.rocks> to test that everything works. Unfortunately, I fell at the first hurdle.

Here is my report for **100: Create an h-entry post (form-encoded)**:

✖ Returned HTTP 201 or 202
✖ Returned a Location header

### Response
```
HTTP/1.1 500 Internal Server Error
Server: Cowboy
Date: Thu, 29 Mar 2018 19:37:14 GMT
Connection: keep-alive
Content-Type: text/html;charset=utf-8
Referrer-Policy: no-referrer
Content-Security-Policy: script-src 'self'
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Set-Cookie: rack.session=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiRTZjZWYxNjQxZmFlZTU2YWE4NDMy%0AZDc3ZTY2Y2I0Y2U4NjY4ZmZiZDdkYzNhNjQ4YTNlYTg0ODE0ZDFlMmZlMmIG%0AOwBGSSIJY3NyZgY7AEZJIjFiTFNsNExUdEd1MHBzY1YzNjZCcWk2ZTlWZkVr%0AMkpIcWJFUVBHd1dUa1VnPQY7AEZJIg10cmFja2luZwY7AEZ7B0kiFEhUVFBf%0AVVNFUl9BR0VOVAY7AFRJIi04NjFmZGE3OTNkYTcyYjIyYjdlN2JkZGE4YmNj%0AOWI2ZTA1ZDg0NmQxBjsARkkiGUhUVFBfQUNDRVBUX0xBTkdVQUdFBjsAVEki%0ALWRhMzlhM2VlNWU2YjRiMGQzMjU1YmZlZjk1NjAxODkwYWZkODA3MDkGOwBG%0A--bc1c8fb7d41069c45823115998cf3ffad92cac6b; path=/; HttpOnly
Content-Length: 223
Via: 1.1 vegur

<!DOCTYPE html>
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta http-equiv="Status" content="500 Error">
</head>
<body>
<h1>500 Error</h1>
<h3>undefined method `store_post&#x27; for nil:NilClass</h3>
</body>
</html>
```

Let me know if you need further information from me to help debug!

**Comment by gerwitz** [comment]
This appears to be because we're not handling unconfigured post types gracefully. I want to have better default behavior and plan better configuration UI, but for now I've tried catching this error more proactively for meaningful reporting.

But no time to test tonight…

**Comment by paulrobertlloyd** [comment]
A-ha! I had created a `note` document flow, not an `entry` document flow. But having created an `entry` flow, I no longer get this error.

**Comment by gerwitz** [comment]
I hope the new error messaging helped you discover this? I'm going to close it in favor of #28

**Comment by paulrobertlloyd** [comment]
I didn’t actually see the error, I just surmised what I had got wrong having seen your comment above! But, more descriptive errors: 👍
