### ISSUE TITLE
Categories not being output

### ISSUE THREAD

**Issue by paulrobertlloyd** [gerwitz/sitewriter#27]
Given test **101: Create an h-entry post with multiple categories (form-encoded)** on <https://micropub.rocks>, which sends this request:

```
POST https://www.sitewriter.net/paulrobertlloyd.com/micropub HTTP/1.1
Authorization: Bearer {{token}}
Content-type: application/x-www-form-urlencoded; charset=utf-8

h=entry&
content=Micropub+test+of+creating+an+h-entry+with+categories.+This+post+should+have+two+categories,+test1+and+test2&
category[]=test1&category[]=test2
```

With the following template:

```
---
date: {{date_time}}
tags:
- microblog
{{#categories}}
- {{name}}
{{/categories}}
---
{{{content}}}

{{#photos}}
![]({{url}})
{{/photos}}
```

The following file is generated:

```
---
date: 2018-03-29T23:13:07+00:00
tags:
- microblog
---
Micropub test of creating an h-entry with categories. This post should have two categories, test1 and test2
```

`test1` and `test2` do not appear under the `categories` front matter key.

**Comment by paulrobertlloyd** [comment]
Ditto **201: Create an h-entry post with multiple categories (JSON)**

(Sorry for the influx of issues/comments; just trying to be though and log any issues as I find them!)

**Comment by gerwitz** [comment]
This is fixed, now, but the templates need to be updated:

Categories are an array of simple values, so instead of `{{name}}` the items should be `{{.}}`

**Comment by gerwitz** [comment]
It was deployed to test.sitewriter.net along with a lot of dangerous refactoring. Some of which seems to have broken auth, so stay tuned.

Sorry for sharing this when it's still pre-alpha!

**Comment by gerwitz** [comment]
I'm recklessly deploying a hot fix all the way to production now.

**Comment by paulrobertlloyd** [comment]
No worries, was just curious!
