### ISSUE TITLE
Add ability to set timezone

### ISSUE THREAD

**Issue by paulrobertlloyd** [gerwitz/sitewriter#36]
I’m currently posting notes where the local timezone (Europe/London) is observing daylight savings (UTC+1). However, posts are being generated using (UTC), so my timestamps are an hour behind. Being able to set my sites timezone would help to solve this situation.

**Comment by gerwitz** [comment]
Interesting … are your posts sending a publication time?

I think I was too quick to assume that using the current time as a default value would be a rare use case.

**Comment by paulrobertlloyd** [comment]
> Interesting … are your posts sending a publication time?

Currently, using Jekyll, if I post manually, I use a ISO 8601 date with the correct timezone offset (`Z`/`+0100`). I also have the `timezone:` key in Jekyll’s config set to `Europe/London`, which essentially figures out the correct hour to use in my note URLs, which use hours and minutes. When posting via Micro.blog, I have no idea what information that’s actually sending… ideally it should be using a timezone based off of my computers clock. I haven’t tried SiteWriter with another Micropub editor yet… if those do the right thing, maybe this is more of a Micro.blog bug than a SiteWriter bug.

**Comment by gerwitz** [comment]
Either way, I think it's sensible.

I plan to:

- [ ] add a per-site timezone setting
- [ ] override that on a per-post basis iff the micropub pubdate includes an offset
- [ ] add a few common datetime formats to the template variables, with "tz", "utc", and "local" options

I think "common datetime formats" will include iso8601 (with `T`) and rfc3339 (with ` `). We might also add a variety of human-readable formats.

**Comment by paulrobertlloyd** [comment]
👋🏻! Until this bug temporarily resolves itself in October, any possibility of getting some sort of fix in place? At the moment I am publishing, then having to quickly edit and commit posts in GitHub. Lots of other features and improvements would be lovely too, but this is the most pressing. (Sorry to be a nag… hope you are well and enjoying the summer!)

**Comment by gerwitz** [comment]
:-| sorry, life is unusually insane this season. But I got a good start on [a branch](https://github.com/gerwitz/sitewriter/tree/timezones) back in May and hope to pick it up again before July ends. Well before October, I hope.

I honestly didn't realize you were using it for real or I would have prioritized!

**Comment by gerwitz** [comment]
Sorry I've been sleeping on this. The project has been on the back-burner while I change careers, but now I'm settling in and want to use it myself more regularly.

**Comment by paulrobertlloyd** [comment]
No worries, totally understandable. But, your deadline is [28th October](https://www.gov.uk/when-do-the-clocks-change) 😉

**Comment by gerwitz** [comment]
As of e8fb712b6f660c8e6e34e51c571e7566f2150aeb  `date_time` has been replaced with `utc_datetime`, and there's a new `utc_epoch`.

All the other date and time variables have been made to respect your chosen timezone setting, which you can set. There's no retroactive auditing, because I imagine this setting reflects "home" for you. If someone wants to manage a travelblog and track timezone they'll have to ask, because handling these things correctly in Ruby is a PITA!

Note that no client seems to send a timestamp, this is all based on the time the processing occurs. ¯\_(ツ)_/¯
