### ISSUE TITLE
Ability to set line feed character/type

### ISSUE THREAD

**Issue by paulrobertlloyd** [gerwitz/sitewriter#37]
SiteWriter writes files using CRLF, but I save my files using LF. The ability to set preferred line break character would be on my nice to have list. 😊

**Comment by gerwitz** [comment]
This is an interesting one. It's getting CRLF from your browser when creating the template. So we'll need to substitute those for LFs.

Maybe encoding should also be an option (UTF-8, US-ASCII)?

**Comment by paulrobertlloyd** [comment]
Curious… so the content that comes from Micro.blog uses LF, but the line breaks in my template use CRLF. I’m using Safari as my browser, so I guess it’s getting its `textarea` settings from there.

**Comment by gerwitz** [comment]
After some investigation, I'm considering just setting everything to LF and waiting for a Windows user to complain loudly enough for a configuration setting. ;-)

**Comment by paulrobertlloyd** [comment]
Seems like the right course, especially given this news: https://betanews.com/2018/05/08/notepad-linux-mac-line-endings/
