### ISSUE TITLE
Creating a post (with a title) with Micro.blog. Title not output.

### ISSUE THREAD

**Issue by paulrobertlloyd** [gerwitz/sitewriter#45]
I created a post using Micro.blog (of an article type since it included a title). And yet, even though I have an article post type configured, and its template contains a title, no title was output. Not sure if I’ve uncovered a bug, here?

**Comment by gerwitz** [comment]
Worked around Heroku's issues with 9209d5fb9e6f1d2f1e51433dfc91236c39c5b3bc and confirmed this was resolved by 52f84886c38cf20312dc894d5ca19ba2acc10828 (using Micropublish.net)
