### ISSUE TITLE
Slug preference

### ISSUE THREAD

**Issue by paulrobertlloyd** [gerwitz/sitewriter#46]
Another site option to consider… if a MicroPub editor doesn’t allow a user to write their own slug, then it’d be nice to have a preference for how slugs should be generated, namely spacing, i.e. should this be achieved using `-` (default) or `_` (which is what I use, and has since fallen out of fashion).

**Comment by gerwitz** [comment]
There is now a `slug_underscore` variable. It will be easy to add other options if anyone needs them, though most scenarios I've seen in the wild can be replicated with the existing variables in combination.

**Comment by paulrobertlloyd** [comment]
Perfecto! Something to include in the forthcoming help/documentation, as this option is not visible in the UI.
