### ISSUE TITLE
Location header not returned

### ISSUE THREAD

**Issue by paulrobertlloyd** [gerwitz/sitewriter#47]
Currently unable to post via Sitewriter. Quill returns the following error:

**Your endpoint did not return a Location header.**
```
HTTP/1.1 500 Internal Server Error
Server: Cowboy
Date: Tue, 08 May 2018 19:19:46 GMT
Connection: keep-alive
Content-Type: text/html;charset=utf-8
Referrer-Policy: no-referrer
Content-Security-Policy: script-src 'self'
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Set-Cookie: rack.session=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiRTY0ZmRiMTJmYjM1ZDBmN2JhMjVk%0AOWZjNTMzNWVlYzAwMzA0NDNiODI1ZmY3MDU4MzA0YmM4NmRjMWFkMmQ4ZTQG%0AOwBGSSIJY3NyZgY7AEZJIjFRdTRYaUdadFFjMGwwQTVDZkp6ZUJTbkdreWVY%0AbXNzamJxS0dla1RmMlFZPQY7AEZJIg10cmFja2luZwY7AEZ7B0kiFEhUVFBf%0AVVNFUl9BR0VOVAY7AFRJIi1kYTM5YTNlZTVlNmI0YjBkMzI1NWJmZWY5NTYw%0AMTg5MGFmZDgwNzA5BjsARkkiGUhUVFBfQUNDRVBUX0xBTkdVQUdFBjsAVEki%0ALWRhMzlhM2VlNWU2YjRiMGQzMjU1YmZlZjk1NjAxODkwYWZkODA3MDkGOwBG%0A--513ea5103d84a1fea269554b12487293a445d043; path=/; HttpOnly
Content-Length: 210
Via: 1.1 vegur

<!DOCTYPE html>
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta http-equiv="Status" content="500 Error">
</head>
<body>
<h1>500 Error</h1>
<h3>comparison of Symbol with Array failed</h3>
</body>
</html>
```

**Comment by gerwitz** [comment]
I foolishly promoted to production right before heading out for dinner. I *think* this is because the new :variable URL template is now in force.

Sorry about that, user #2! I will diagnose in earnest in the morning (GMT+1)

**Comment by paulrobertlloyd** [comment]
I thought it might be that. Having seen that this change had been pushed, I updated my URL templates, but still got the same error. Hmmm 🤔

Riker, out!

![](https://media.giphy.com/media/PJWKBfhzrwKtO/giphy.gif)

**Comment by gerwitz** [comment]
Better error handling in place, now at least you should be told *how* it's failing.

But this will be fun to solve. The new pattern syntax is provided by Mustermann (same library Jekyll uses) but the error is being thrown…in its own error handling! My favorite type of bug.

Still, hopefully I have this resolved this morning.

**Comment by gerwitz** [comment]
I've reproduced and then resolved this, so I think we're good. Let me know if I need to re-open this!
