### ISSUE TITLE
undefined method `post_kind&#x27; for nil:NilClass

### ISSUE THREAD

**Issue by paulrobertlloyd** [gerwitz/sitewriter#53]
Hmmm, still having problems. Posting via Micro.blog apps doesn’t work, fortunately attempting the same via Quill gives some feedback. This is what was returned when using the Editor in Quill (not sure what post kind the relates to mind).

```
HTTP/1.1 100 Continue

HTTP/1.1 500 Internal Server Error
Server: Cowboy
Date: Wed, 09 May 2018 17:39:32 GMT
Connection: keep-alive
Content-Type: text/html;charset=utf-8
Referrer-Policy: no-referrer
Content-Security-Policy: script-src 'self'
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Set-Cookie: rack.session=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiRWVmZjYwOWE4MDY3ZDhlMTU4MWM2%0AMGVjZDQzZjRjNzQ5ZGZmYzk5ZDBkMWI3ZDA0ZTc4MmU1Y2ZkNmE0MzI1MmYG%0AOwBGSSIJY3NyZgY7AEZJIjFtU08yYXJoSlZWa2ExSmVmOEFGdTg5b1JTNFlr%0AblBBNVVSMms1RVdrYUVVPQY7AEZJIg10cmFja2luZwY7AEZ7B0kiFEhUVFBf%0AVVNFUl9BR0VOVAY7AFRJIi1kYTM5YTNlZTVlNmI0YjBkMzI1NWJmZWY5NTYw%0AMTg5MGFmZDgwNzA5BjsARkkiGUhUVFBfQUNDRVBUX0xBTkdVQUdFBjsAVEki%0ALWRhMzlhM2VlNWU2YjRiMGQzMjU1YmZlZjk1NjAxODkwYWZkODA3MDkGOwBG%0A--6c3bfd88d660ad05977c4cef2543bfcb31ea115e; path=/; HttpOnly
Content-Length: 222
Via: 1.1 vegur

<!DOCTYPE html>
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta http-equiv="Status" content="500 Error">
</head>
<body>
<h1>500 Error</h1>
<h3>undefined method `post_kind&#x27; for nil:NilClass</h3>
</body>
</html>
```

**Comment by gerwitz** [comment]
Your post seems to have confused my post type discovery heuristics. Which is going to be a challenge since the data you sent triggers `article` in my testing. Stay tuned and thanks for continuing to break things!

**Comment by gerwitz** [comment]
@paulrobertlloyd I have a very stupid question: how are you using Quill to send posts with a title?

**Comment by paulrobertlloyd** [comment]
As I wanted to send a note with a title (and if that got resolved with type of article/post, then so be it), I used the Editor (https://quill.p3k.io/editor), as opposed to the Note UI (https://quill.p3k.io/new).

**Comment by gerwitz** [comment]
Ah, I forgot that "editor" isn't just for updating!

I've used it to make several updates to test sites, now. And put in some extra logging and error checking. So please try it again when you have another titled post to try?

**Comment by gerwitz** [comment]
I haven't seen this recur in the logs, so will close this off my to-do list.
