### ISSUE TITLE
Checkin post variables

### ISSUE THREAD

**Issue by gerwitz** [gerwitz/sitewriter#56]
Using OwnYourSwarm as a reference implementation.

A checkin is like a note but includes a `checkin` variable that will have exactly the same structure as a `location` (see #68).

It's possible but not expected that a checkin post would also include a location.

See also https://indieweb.org/checkin

Note that https://ownyourcheckin.wirres.net/ uses a different Micropub format and isn't well documented, so we won't support it.

**Comment by paulrobertlloyd** [comment]
👍 to Liquid and a dotted hierarchy.

**Comment by gerwitz** [comment]
Maybe we should use "location" for latitude and longitude to match the media post types. But these come from different properties than OYS checkins, so maybe not?

**Comment by paulrobertlloyd** [comment]
Could `location` be a variable much like `year_month` which is sort of like a helper variable. So `location` would essentially return “`venue-latitude`,`venue-longitude`”. Maybe.

**Comment by gerwitz** [comment]
I like that, but is this preferable to names?

I suggest a heuristic that uses the first value of:
- venue.name
- venue.region
- venue.county
- venue.latitude, venue.longitude
- "unknown"

**Comment by paulrobertlloyd** [comment]
Not sure I quite follow. Having seen the JSON OwnYourSwarm generates, I’ve mocked up the output I would like to generate, which you can see here: https://github.com/paulrobertlloyd/paulrobertlloyd-v4/blob/master/src/_content/checkins/2018-05-11-1417.md Maybe this will help you figure out the best way forward.

**Comment by gerwitz** [comment]
Thanks, that was helpful and convinced me to include locality, et al. I'm rewriting the plan above…

**Comment by gerwitz** [comment]
Built to work according to OwnYourSwarm docs, but only briefly tested with Micropublish.
