### ISSUE TITLE
Include post type in commit message

### ISSUE THREAD

**Issue by paulrobertlloyd** [gerwitz/sitewriter#67]
Currently all post types say `Adding new post via sitewriter.net`. They should probably use the respective post type, i.e.`Adding new checkin via sitewriter.net`. Also… I wonder if this could be reformatted as:

`New [post-type] (added via sitewriter.net)`

But that’s just me being nit-picky!

**Comment by gerwitz** [comment]
Good idea, and nice to do this before there are too many saving options to modify.

Implemented in c2d1559a4d610f46ea1859f2c2acec44e466a6c2
