### ISSUE TITLE
Unexpected server error (NoMethodError)

### ISSUE THREAD

**Issue by paulrobertlloyd** [gerwitz/sitewriter#70]
Getting the following error when signing in and viewing https://sitewriter.net/paulrobertlloyd.com/

```
{"error":"server_error","error_description":"Unexpected server error (NoMethodError)."}
```

**Comment by paulrobertlloyd** [comment]
Not getting the same error on test.sitewriter.net, but I suspect that is because my setup is different, and I haven’t posted anything to that endpoint.

**Comment by gerwitz** [comment]
Deploying a fix to production now, try again?

**Comment by paulrobertlloyd** [comment]
…and we’re back! Thanks for the quick fix!

**Comment by gerwitz** [comment]
That was an amateur mistake on my part! Time to prioritize some test scripts…
