### ISSUE TITLE
Improved error reporting

### ISSUE THREAD

**Issue by paulrobertlloyd** [gerwitz/sitewriter#75]
Currently the status page provides minimal information about errors, typically: `forbidden` error. It would be helpful to see a more detailed error log (if available) to better understand what’s gone wrong in these instances.

**Comment by gerwitz** [comment]
The title attribute on the error in the logs should give you the exception's message. But that's the same as what it's returning to the client (which Quill will show you).

I'm going to have to try reproducing the forbidden error. Do you mind if I look into your site configuration directly?

**Comment by paulrobertlloyd** [comment]
Ah, this wasn’t at all clear to me. Have submitted #77 as a possible means of making the full error message more accessible.
