### ISSUE TITLE
Option to use local date time variable in templates

### ISSUE THREAD

**Issue by paulrobertlloyd** [gerwitz/sitewriter#80]
Sorry, back again with another data time request! First of all, the new timezone setting is working a treat, thank-you! However, I like to save the datetime value in my posts using a timezone offset, as it provides a bit more context. So whereas currently I can generate this:

```
---
date: 2018-10-25T17:31:10+00:00
---
```

Given I have set my timezone as `Europe - London`, I would like to generate this:

```
---
date: 2018-10-25T18:31:10+01:00
---
```

Is this possible at all? Perhaps using a `local_datetime` or just `datetime` variable?

**Comment by gerwitz** [comment]
I wanted this, too, but it was too hard.

Then a user asks for it, and it's worth the effort.

**Comment by paulrobertlloyd** [comment]
Excellent! Haven’t had a chance to test this yet, and guess won’t for another six months or my next trip, but thanks so much for addressing this so quickly!
