### ISSUE TITLE
How can I change GitHub repository linked to a domain?

### ISSUE THREAD

**Issue by paulrobertlloyd** [gerwitz/sitewriter#81]
I have recently updated my the design of my site, with the code saved in a new repository. This means I need to save posts to a different repo, but there seems to be no way of editing this value. Help!!

**Comment by paulrobertlloyd** [comment]
Looking at the code, there seems to be `/[domain]/stores/new`, but adding values here has no effect. Maybe there should be `/[domain]/stores/[id]` or similar where I can view and edit an existing store?

**Comment by paulrobertlloyd** [comment]
Oops, didn’t see the delete link, forgive my haste! However, in trying that, I got the following error:

```
{"error":"server_error","error_description":"Unexpected server error (Sequel::ForeignKeyConstraintViolation)."}
```

**Comment by gerwitz** [comment]
Oops! Your config was old enough it still had "stores" associated directly with "flows" … which the current UI doesn't support. (I left the DB structure in place for possible future fancy situations, but that's probably not so wise.)

I fixed that in the DB, so you can delete when you'd like to.

**Comment by gerwitz** [comment]
Cowboy patch being promoted now, I'll leave this open until you confirm it's working for you.

**Comment by paulrobertlloyd** [comment]
Have been able to edit my config, will confirm everything works when I next post. Thanks for the fix!

**Comment by paulrobertlloyd** [comment]
Regarding this issue, can confirm that editing now works and I can post.
