### ISSUE TITLE
What are bookmark variable for name and url ?

### ISSUE THREAD

**Issue by alienlebarge** [gerwitz/sitewriter#83]
### Description

I post bookmarks from [Quill](https://quill.p3k.io/) where I can put the following informations:
- Bookmark URL
- Name
- Content
- Tags

Sitewriter do not get the info of *Bookmark URL* and  *Name* because I can't find wich variable to use in the template.

### Ask

Is there any variable I can use to get the information of bookmark's title and url ?

### Additional Info

![Napkin 6 24 04 19, 8 54 06 AM](https://user-images.githubusercontent.com/611234/56638448-84aee180-666e-11e9-8d54-5211118a7cf7.png)

My sitewriter bookmark template (where *title* and *url* do not work):
```
---
title: {{title}}
date: {{datetime}}
url: {{url}}
tags:
{{#categories}}
- {{.}}
{{/categories}}
---
{{content}}
```

***

And thanks for this incredible website. You rocks  :raised_hands:

**Comment by gerwitz** [comment]
I never finished/tested bookmarks!

You should now see `name` and `url` as variables. I've tested with Quill, but only lightly.
