### ISSUE TITLE
Template error on likes

### ISSUE THREAD

**Issue by EdwinWenink** [gerwitz/sitewriter#90]
When sending likes to Sitewriter.net I get a template error:

"Unable to generate file path: undefined local variable or method `time' for #
Did you mean?  timeout"

This occurs both for micropub likes sent with OmniBear and with https://micropublish.net. 
I can't find out what the issue is.

FYI: Sending bookmarks to my domain works perfectly, so my issue is specific to receiving "likes"

**Comment by gerwitz** [comment]
Hi! I have never tested likes, but now that there’s an interested user I’ll get it working…

**Comment by alienlebarge** [comment]
Hi,
Same error when importing checkins via [ownyourswarm](https://ownyourswarm.p3k.io/)
![Capture d’écran 2019-06-03 à 20 52 11](https://user-images.githubusercontent.com/611234/58826681-868e9c00-8641-11e9-97af-dda4b1eb10ff.png)
![Capture d’écran 2019-06-03 à 20 52 30-fullpage](https://user-images.githubusercontent.com/611234/58826692-8b535000-8641-11e9-8804-42bbf659dee2.png)

**Comment by gerwitz** [comment]
That’s a puzzling one at first glance. I’m at a conference at the moment, but will try to find time to look into this.

**Comment by gerwitz** [comment]
This bug has been resolved, but I'm still working on #60 and #56 so likes and checkins will work.
