### ISSUE TITLE
Read out name and target url for replies

### ISSUE THREAD

**Issue by EdwinWenink** [gerwitz/sitewriter#91]
I want to read out the name and target url of a Micropub reply. 
In the case of bookmarks, I managed to do that using the following template:

```
---
title: {{name}}
date: {{utc_datetime}}
slug: {{slug}}
target: {{url}}
---
{{{content}}}
```

However in the case of replies both `title: {{name}}` and  `target: {{url}}` return an empty field.

**Comment by gerwitz** [comment]
Another post type that hasn’t been well tested. I’ll look for a good tool for generating these requests and get this working soon.

**Comment by gerwitz** [comment]
Most of the samples I can find do not include a title (name) … what did you have in mind for this field?

Technically we should support including a title, but I suspect you are hoping for the title of the post being replied too. Unfortunately, that's going to be deep in the backlog since it will require fetching and parsing the target URL which comes with a lot of security risks.

**Comment by gerwitz** [comment]
Based on some quick testing, this seems to work now. I'll improve the sample template soon,

**Comment by EdwinWenink** [comment]
I indeed meant the title of the post I'm replying to. It is already included in the message sent for example from Omnibear to Sitewriter. 

I cannot test this right now though. When logging in to the public instance, pressing on any of the "settings" buttons gives me the following error:

```
{"error":"server_error","error_description":"Unexpected server error (NoMethodError)."}
```

Also it seems that the whole "reply" response type disappeared alltogether from the dashboard.
Would you like me to open a new issue for this?

**Comment by gerwitz** [comment]
I may have to fake authentication as you to debug that error, I hope you don't mind?

Yes, please add an issue for "reply" … I decided to hide all the types I haven't even tried in hopes users would make requests as needed. :-)

**Comment by EdwinWenink** [comment]
Can you elaborate on what you exactly mean by "faking authentication" as me? 

Do note that I did open this issue already specifically for the reply response type :-)

**Comment by EdwinWenink** [comment]
It seems your latest commit fixed it for me. I can access the settings again.

**Comment by gerwitz** [comment]
Ha! You did. Somehow I thought this was about "like".

I'm enabling "reply" for you now.

**Comment by gerwitz** [comment]
Alright, it's back with `original_url` (from `in-reply-to`) and `title` (from `name`). I disabled attachments, but I see that some clients allow photo replies so maybe that will change.

It seems like there should be a "quoted content" or other field, but I can't find any de-facto standard for it, I suppose `content` is used for that with quoting.

**Comment by EdwinWenink** [comment]
Thanks! I'll have time to test it later and will let you know if I encounter issues.
