### ISSUE TITLE
Support for "reply" response type

### ISSUE THREAD

**Issue by EdwinWenink** [gerwitz/sitewriter#94]
I would like to be able to receive micropub responses through SiteWriter. 
In particular I would like it if SiteWriter could also read out the target url of the reply, because for each micropub reply on my website I also want to display the url it is a response to.

See the following url for an example of what I have in mind: https://www.edwinwenink.xyz/micro/nos-discriminatie-voorspellende-algoritmes/

**Comment by gerwitz** [comment]
Should have been resolved with #91

**Comment by EdwinWenink** [comment]
Confirmed! Nice work. The following reply is succesfully processed by SiteWriter: https://www.edwinwenink.xyz/micro/this-reply-is-processed-by-sitewriter/
